name: piecemeal
version: 0.4.1
author: Bob Nystrom <robert@stuffwithstuff.com>
description: Basic data structures your 2D game may need.
homepage: https://github.com/munificent/piecemeal
dev_dependencies:
  test: any
environment:
  sdk: ">=2.0.0-dev.62.0 <3.0.0"
