name: piecemeal
version: 0.3.2
author: Bob Nystrom <robert@stuffwithstuff.com>
description: Basic data structures your 2D game may need.
homepage: https://github.com/munificent/piecemeal
dev_dependencies:
  test: any
environment:
  sdk: ">=1.24.0 <2.0.0"
