name: piecemeal
version: 2.0.0
description: Basic data structures for your 2D game.
homepage: https://github.com/munificent/piecemeal
dev_dependencies:
  lints: any
  test: any
environment:
  sdk: "^3.0.0"
topics:
  - game
  - math
  - 2d
  - random
