name: piecemeal
version: 2.0.0-dev
description: Basic data structures your 2D game may need.
homepage: https://github.com/munificent/piecemeal
dev_dependencies:
  lints: any
  test: any
environment:
  sdk: "^3.0.0"
